export const MOCK_VENDORS = [
  {
    id: 'v1',
    name: 'La Carnicería El Rancho',
    slug: 'el-rancho',
    description: 'Family-owned since 1987. Best carne asada in San Jose, marinated with our secret citrus blend passed down three generations.',
    rating: 4.9,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1558030006-450675393462?w=1200&auto=format&fit=crop',
    city: 'San Jose',
    address: '1420 Story Rd, San Jose, CA 95122',
    phone: '(408) 555-0192',
    hours: 'Mon–Sat 7am–7pm, Sun 7am–5pm',
    deliveryZones: ['San Jose', 'Santa Clara', 'Milpitas'],
    minOrder: 2,
    estimatedDelivery: '30–45 min',
    isOpen: true,
    specialties: ['Carne Asada', 'Chorizo', 'Tripas'],
    ownerId: 'vendor-user-1',
  },
  {
    id: 'v2',
    name: 'Carnitas La Familia',
    slug: 'la-familia',
    description: 'Authentic Michoacán-style carnitas cooked in copper pots. Our al pastor is marinated 24 hours with fresh pineapple and guajillo chiles.',
    rating: 4.8,
    reviewCount: 217,
    image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&auto=format&fit=crop',
    city: 'Oakland',
    address: '2890 Fruitvale Ave, Oakland, CA 94601',
    phone: '(510) 555-0348',
    hours: 'Tue–Sun 6am–6pm',
    deliveryZones: ['Oakland', 'Alameda', 'Hayward'],
    minOrder: 3,
    estimatedDelivery: '35–50 min',
    isOpen: true,
    specialties: ['Carnitas', 'Al Pastor', 'Short Ribs'],
    ownerId: 'vendor-user-2',
  },
  {
    id: 'v3',
    name: 'El Toro Meat Market',
    slug: 'el-toro',
    description: 'Premium USDA Choice and Prime cuts. Our carne asada is dry-aged for tenderness and marinated in a blend of citrus, garlic, and Mexican spices.',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1432139555190-58524dae6a55?w=1200&auto=format&fit=crop',
    city: 'Los Angeles',
    address: '3456 E Cesar Chavez Ave, Los Angeles, CA 90063',
    phone: '(323) 555-0721',
    hours: 'Mon–Sun 6am–8pm',
    deliveryZones: ['Los Angeles', 'Boyle Heights', 'East LA'],
    minOrder: 2,
    estimatedDelivery: '25–40 min',
    isOpen: true,
    specialties: ['Carne Asada', 'Short Ribs', 'Lengua'],
    ownerId: 'vendor-user-3',
  },
  {
    id: 'v4',
    name: 'Carnicería San Miguel',
    slug: 'san-miguel',
    description: 'Straight from Jalisco. Traditional recipes using only locally-sourced beef and pork. Our chorizo is made fresh every morning.',
    rating: 4.6,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop',
    city: 'San Diego',
    address: '892 National Ave, San Diego, CA 92113',
    phone: '(619) 555-0456',
    hours: 'Mon–Sat 7am–7pm',
    deliveryZones: ['San Diego', 'Chula Vista', 'National City'],
    minOrder: 2,
    estimatedDelivery: '30–45 min',
    isOpen: false,
    specialties: ['Chorizo', 'Carnitas', 'Pollo'],
    ownerId: 'vendor-user-4',
  },
]

export const MOCK_PRODUCTS = {
  v1: [
    {
      id: 'p1-1',
      vendorId: 'v1',
      name: 'Carne Asada Premium',
      category: 'carne-asada',
      description: 'USDA Choice flank steak marinated in our secret citrus-garlic blend. Perfect for tacos, burritos, or on the grill.',
      pricePerLb: 12.99,
      image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 45,
      options: { marinade: true, cut: true },
      popular: true,
    },
    {
      id: 'p1-2',
      vendorId: 'v1',
      name: 'Chorizo Rojo',
      category: 'chorizo',
      description: 'Freshly made pork chorizo with guajillo and ancho chiles. No preservatives, made daily.',
      pricePerLb: 8.99,
      image: 'https://images.unsplash.com/photo-1592415499556-74fcb9f18667?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 30,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p1-3',
      vendorId: 'v1',
      name: 'Short Ribs / Costillas',
      category: 'short-ribs',
      description: 'Meaty bone-in short ribs, ideal for slow braising or BBQ. Cut flanken-style or English-style.',
      pricePerLb: 10.49,
      image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 22,
      options: { marinade: true, cut: true },
      popular: false,
    },
    {
      id: 'p1-4',
      vendorId: 'v1',
      name: 'Tripas',
      category: 'tripas',
      description: 'Cleaned and ready-to-cook beef tripas. Crispy on the grill, amazing in tacos.',
      pricePerLb: 7.99,
      image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 18,
      options: { marinade: false, cut: false },
      popular: false,
    },
  ],
  v2: [
    {
      id: 'p2-1',
      vendorId: 'v2',
      name: 'Carnitas Michoacán',
      category: 'carnitas',
      description: 'Slow-cooked pork in copper pots the traditional Michoacán way. Crispy ends, tender inside.',
      pricePerLb: 11.99,
      image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 35,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p2-2',
      vendorId: 'v2',
      name: 'Al Pastor',
      category: 'al-pastor',
      description: '24-hour marinated pork with pineapple, guajillo, and achiote. Cut from the trompo fresh to order.',
      pricePerLb: 10.99,
      image: 'https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 28,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p2-3',
      vendorId: 'v2',
      name: 'Short Ribs BBQ',
      category: 'short-ribs',
      description: 'BBQ-style flanken short ribs marinated in our house sauce. Ready for the grill.',
      pricePerLb: 13.49,
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 15,
      options: { marinade: true, cut: true },
      popular: false,
    },
  ],
  v3: [
    {
      id: 'p3-1',
      vendorId: 'v3',
      name: 'Prime Carne Asada',
      category: 'carne-asada',
      description: 'USDA Prime dry-aged skirt steak. The best quality carne asada in LA, marinated in our house blend.',
      pricePerLb: 15.99,
      image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 40,
      options: { marinade: true, cut: true },
      popular: true,
    },
    {
      id: 'p3-2',
      vendorId: 'v3',
      name: 'Beef Short Ribs',
      category: 'short-ribs',
      description: 'Premium bone-in beef short ribs. Perfect for carne en su jugo or Korean-style BBQ.',
      pricePerLb: 14.99,
      image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 25,
      options: { marinade: true, cut: true },
      popular: true,
    },
    {
      id: 'p3-3',
      vendorId: 'v3',
      name: 'Lengua',
      category: 'lengua',
      description: 'Slow-cooked beef tongue, tender and ready for tacos or tortas.',
      pricePerLb: 9.99,
      image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 12,
      options: { marinade: false, cut: false },
      popular: false,
    },
  ],
  v4: [
    {
      id: 'p4-1',
      vendorId: 'v4',
      name: 'Chorizo Verde',
      category: 'chorizo',
      description: 'Green chorizo made with fresh poblano, tomatillo, and herbs. A Jalisco specialty.',
      pricePerLb: 9.49,
      image: 'https://images.unsplash.com/photo-1592415499556-74fcb9f18667?w=600&auto=format&fit=crop',
      inStock: false,
      stockLbs: 0,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p4-2',
      vendorId: 'v4',
      name: 'Carnitas Jalisco',
      category: 'carnitas',
      description: 'Jalisco-style fried pork with crispy skin. Made fresh every morning.',
      pricePerLb: 11.49,
      image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=600&auto=format&fit=crop',
      inStock: false,
      stockLbs: 0,
      options: { marinade: false, cut: false },
      popular: false,
    },
  ],
}

export const MOCK_ORDERS = [
  {
    id: 'ord-001',
    customerId: 'customer-user-1',
    vendorId: 'v1',
    vendorName: 'La Carnicería El Rancho',
    driverId: 'driver-user-1',
    driverName: 'Carlos M.',
    items: [
      { productId: 'p1-1', name: 'Carne Asada Premium', pricePerLb: 12.99, quantity: 3, marinade: 'traditional', cut: 'thin' },
      { productId: 'p1-2', name: 'Chorizo Rojo', pricePerLb: 8.99, quantity: 1, marinade: null, cut: null },
    ],
    subtotal: 47.96,
    serviceFee: 2.40,
    deliveryFee: 4.99,
    total: 55.35,
    status: 'picked_up',
    address: '500 El Camino Real, San Jose, CA',
    createdAt: new Date(Date.now() - 25 * 60000),
    estimatedDelivery: '5–15 min',
    paymentMethod: 'card',
    paymentLast4: '4242',
  },
  {
    id: 'ord-002',
    customerId: 'customer-user-1',
    vendorId: 'v2',
    vendorName: 'Carnitas La Familia',
    driverId: 'driver-user-2',
    driverName: 'Miguel R.',
    items: [
      { productId: 'p2-1', name: 'Carnitas Michoacán', pricePerLb: 11.99, quantity: 4, marinade: null, cut: null },
    ],
    subtotal: 47.96,
    serviceFee: 2.40,
    deliveryFee: 4.99,
    total: 55.35,
    status: 'delivered',
    address: '500 El Camino Real, San Jose, CA',
    createdAt: new Date(Date.now() - 2 * 24 * 3600000),
    estimatedDelivery: 'Delivered',
    paymentMethod: 'card',
    paymentLast4: '4242',
  },
]

export const MOCK_DRIVER_DELIVERIES = [
  {
    id: 'del-001',
    orderId: 'ord-001',
    driverId: 'driver-user-1',
    status: 'picked_up',
    vendorName: 'La Carnicería El Rancho',
    vendorAddress: '1420 Story Rd, San Jose, CA 95122',
    customerName: 'Maria G.',
    customerAddress: '500 El Camino Real, San Jose, CA 95008',
    customerPhone: '(408) 555-0199',
    items: '3 lbs Carne Asada + 1 lb Chorizo',
    earning: 8.50,
    pickupTime: new Date(Date.now() - 15 * 60000),
    estimatedDropoff: '5–10 min',
  },
]

export const MOCK_USERS = {
  customer: {
    id: 'customer-user-1',
    email: 'customer@demo.com',
    password: 'demo123',
    name: 'Maria García',
    role: 'customer',
    phone: '(408) 555-0199',
    address: '500 El Camino Real, San Jose, CA 95008',
    avatar: null,
  },
  vendor: {
    id: 'vendor-user-1',
    email: 'vendor@demo.com',
    password: 'demo123',
    name: 'Roberto Hernández',
    role: 'vendor',
    vendorId: 'v1',
    phone: '(408) 555-0192',
    avatar: null,
  },
  driver: {
    id: 'driver-user-1',
    email: 'driver@demo.com',
    password: 'demo123',
    name: 'Carlos Mendoza',
    role: 'driver',
    phone: '(408) 555-0288',
    vehicle: 'Toyota Corolla — Silver',
    licensePlate: '7ABC123',
    avatar: null,
    isOnline: true,
  },
}
