export const MOCK_VENDORS = [
  {
    id: 'v1',
    name: 'La Carnicería El Rancho',
    slug: 'el-rancho',
    description: 'Family-owned since 1987. Best carne asada in San Jose, marinated with our secret citrus blend passed down three generations. Party trays delivered fresh to your door.',
    rating: 4.9,
    reviewCount: 342,
    image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=1200&auto=format&fit=crop',
    city: 'San Jose',
    address: '1420 Story Rd, San Jose, CA 95122',
    phone: '(408) 555-0192',
    hours: 'Mon–Sat 7am–7pm, Sun 7am–5pm',
    deliveryZones: ['San Jose', 'Santa Clara', 'Milpitas'],
    minOrder: 2,
    estimatedDelivery: '30–45 min',
    isOpen: true,
    specialties: ['Trays', 'Carne Asada', 'Chorizo'],
    ownerId: 'vendor-user-1',
  },
  {
    id: 'v2',
    name: 'Carnitas La Familia',
    slug: 'la-familia',
    description: 'Authentic Michoacán-style carnitas cooked in copper pots. Our party trays feed the whole family. Al pastor marinated 24 hours with fresh pineapple and guajillo chiles.',
    rating: 4.8,
    reviewCount: 217,
    image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=1200&auto=format&fit=crop',
    city: 'Oakland',
    address: '2890 Fruitvale Ave, Oakland, CA 94601',
    phone: '(510) 555-0348',
    hours: 'Tue–Sun 6am–6pm',
    deliveryZones: ['Oakland', 'Alameda', 'Hayward'],
    minOrder: 3,
    estimatedDelivery: '35–50 min',
    isOpen: true,
    specialties: ['Trays', 'Carnitas', 'Al Pastor'],
    ownerId: 'vendor-user-2',
  },
  {
    id: 'v3',
    name: 'El Toro Meat Market',
    slug: 'el-toro',
    description: 'Premium USDA Prime & Wagyu cuts. Our carne asada trays are dry-aged for tenderness, marinated in citrus, garlic, and Mexican spices. Restaurant quality at home.',
    rating: 4.7,
    reviewCount: 189,
    image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=1200&auto=format&fit=crop',
    city: 'Los Angeles',
    address: '3456 E Cesar Chavez Ave, Los Angeles, CA 90063',
    phone: '(323) 555-0721',
    hours: 'Mon–Sun 6am–8pm',
    deliveryZones: ['Los Angeles', 'Boyle Heights', 'East LA'],
    minOrder: 2,
    estimatedDelivery: '25–40 min',
    isOpen: true,
    specialties: ['Trays', 'Wagyu', 'Carne Asada'],
    ownerId: 'vendor-user-3',
  },
  {
    id: 'v4',
    name: 'Carnicería San Miguel',
    slug: 'san-miguel',
    description: 'Straight from Jalisco. Traditional recipes using only locally-sourced beef and pork. Fiesta trays made fresh every morning — perfect for any celebration.',
    rating: 4.6,
    reviewCount: 143,
    image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=800&auto=format&fit=crop',
    coverImage: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=1200&auto=format&fit=crop',
    city: 'San Diego',
    address: '892 National Ave, San Diego, CA 92113',
    phone: '(619) 555-0456',
    hours: 'Mon–Sat 7am–7pm',
    deliveryZones: ['San Diego', 'Chula Vista', 'National City'],
    minOrder: 2,
    estimatedDelivery: '30–45 min',
    isOpen: false,
    specialties: ['Trays', 'Chorizo', 'Carnitas'],
    ownerId: 'vendor-user-4',
  },
]

export const MOCK_PRODUCTS = {
  v1: [
    {
      id: 'p1-t1',
      vendorId: 'v1',
      name: 'Carne Asada Party Tray',
      category: 'trays',
      unit: 'tray',
      description: '5 lbs of USDA Choice carne asada marinated in our secret citrus-garlic blend. Feeds 8–10 people. Delivered ready to grill.',
      pricePerLb: 64.99,
      image: 'https://images.unsplash.com/photo-1529692236671-f1f6cf9683ba?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 20,
      options: { marinade: true, cut: false },
      popular: true,
    },
    {
      id: 'p1-t2',
      vendorId: 'v1',
      name: 'BBQ Mix Tray',
      category: 'trays',
      unit: 'tray',
      description: '8 lbs mixed — carne asada, short ribs & chorizo. Feeds 12–15 people. Our best-selling tray for quinceañeras and carne asadas.',
      pricePerLb: 99.99,
      image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 12,
      options: { marinade: true, cut: false },
      popular: true,
    },
    {
      id: 'p1-1',
      vendorId: 'v1',
      name: 'Carne Asada Premium',
      category: 'carne-asada',
      description: 'USDA Choice flank steak marinated in our secret citrus-garlic blend. Perfect for tacos, burritos, or on the grill.',
      pricePerLb: 12.99,
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 45,
      options: { marinade: true, cut: true },
      popular: false,
    },
    {
      id: 'p1-2',
      vendorId: 'v1',
      name: 'Chorizo Rojo',
      category: 'chorizo',
      description: 'Freshly made pork chorizo with guajillo and ancho chiles. No preservatives, made daily.',
      pricePerLb: 8.99,
      image: 'https://images.unsplash.com/photo-1592415499556-74fcb9f18667?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 30,
      options: { marinade: false, cut: false },
      popular: false,
    },
    {
      id: 'p1-3',
      vendorId: 'v1',
      name: 'Short Ribs / Costillas',
      category: 'short-ribs',
      description: 'Meaty bone-in short ribs, ideal for slow braising or BBQ. Cut flanken-style or English-style.',
      pricePerLb: 10.49,
      image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 22,
      options: { marinade: true, cut: true },
      popular: false,
    },
  ],
  v2: [
    {
      id: 'p2-t1',
      vendorId: 'v2',
      name: 'Carnitas Family Tray',
      category: 'trays',
      unit: 'tray',
      description: '5 lbs of Michoacán-style carnitas slow-cooked in copper pots. Crispy ends, tender inside. Feeds 8–10 people.',
      pricePerLb: 59.99,
      image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 15,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p2-t2',
      vendorId: 'v2',
      name: 'Al Pastor Party Tray',
      category: 'trays',
      unit: 'tray',
      description: '5 lbs of 24-hour marinated al pastor with pineapple, guajillo & achiote. Feeds 8–10. Cut fresh from the trompo.',
      pricePerLb: 64.99,
      image: 'https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 10,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p2-t3',
      vendorId: 'v2',
      name: 'Party Mixto Tray',
      category: 'trays',
      unit: 'tray',
      description: '10 lbs mixed carnitas, al pastor & short ribs. Feeds 15–20 people. Perfect for large gatherings and family events.',
      pricePerLb: 119.99,
      image: 'https://images.unsplash.com/photo-1551218808-94e220e084d2?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 8,
      options: { marinade: false, cut: false },
      popular: false,
    },
    {
      id: 'p2-1',
      vendorId: 'v2',
      name: 'Carnitas Michoacán',
      category: 'carnitas',
      description: 'Slow-cooked pork in copper pots the traditional Michoacán way. Crispy ends, tender inside.',
      pricePerLb: 11.99,
      image: 'https://images.unsplash.com/photo-1504544750208-dc0358e63f7f?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 35,
      options: { marinade: false, cut: false },
      popular: false,
    },
    {
      id: 'p2-2',
      vendorId: 'v2',
      name: 'Al Pastor',
      category: 'al-pastor',
      description: '24-hour marinated pork with pineapple, guajillo, and achiote. Cut from the trompo fresh to order.',
      pricePerLb: 10.99,
      image: 'https://images.unsplash.com/photo-1618449840665-9ed506d73a34?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 28,
      options: { marinade: false, cut: false },
      popular: false,
    },
  ],
  v3: [
    {
      id: 'p3-t1',
      vendorId: 'v3',
      name: 'USDA Prime Carne Asada Tray',
      category: 'trays',
      unit: 'tray',
      description: '5 lbs USDA Prime dry-aged skirt steak, marinated in our house blend. Feeds 8–10 people. Restaurant quality delivered.',
      pricePerLb: 79.99,
      image: 'https://images.unsplash.com/photo-1558030006-450675393462?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 14,
      options: { marinade: true, cut: false },
      popular: true,
    },
    {
      id: 'p3-t2',
      vendorId: 'v3',
      name: 'A5 Wagyu Tray',
      category: 'trays',
      unit: 'tray',
      description: '3 lbs of A5 Japanese Wagyu beef — extraordinary marbling, melt-in-your-mouth texture. Feeds 4–6 people. The ultimate luxury tray.',
      pricePerLb: 89.99,
      image: 'https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 6,
      options: { marinade: false, cut: true },
      popular: true,
    },
    {
      id: 'p3-t3',
      vendorId: 'v3',
      name: 'Short Rib Tray',
      category: 'trays',
      unit: 'tray',
      description: '5 lbs premium bone-in short ribs, flanken-cut and marinated. Feeds 8–10. Perfect for Korean-style BBQ or carne en su jugo.',
      pricePerLb: 84.99,
      image: 'https://images.unsplash.com/photo-1603360946369-dc9bb6258143?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 10,
      options: { marinade: true, cut: false },
      popular: false,
    },
    {
      id: 'p3-1',
      vendorId: 'v3',
      name: 'Prime Carne Asada',
      category: 'carne-asada',
      description: 'USDA Prime dry-aged skirt steak. The best quality carne asada in LA, marinated in our house blend.',
      pricePerLb: 15.99,
      image: 'https://images.unsplash.com/photo-1544025162-d76694265947?w=600&auto=format&fit=crop',
      inStock: true,
      stockLbs: 40,
      options: { marinade: true, cut: true },
      popular: false,
    },
  ],
  v4: [
    {
      id: 'p4-t1',
      vendorId: 'v4',
      name: 'Weekend Fiesta Tray',
      category: 'trays',
      unit: 'tray',
      description: '10 lbs mixed — carnitas, chorizo, and carne asada. Feeds 15–20. Made fresh every morning. The ultimate party tray from Jalisco.',
      pricePerLb: 109.99,
      image: 'https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?w=600&auto=format&fit=crop',
      inStock: false,
      stockLbs: 0,
      options: { marinade: false, cut: false },
      popular: true,
    },
    {
      id: 'p4-t2',
      vendorId: 'v4',
      name: 'Chorizo + Carnitas Tray',
      category: 'trays',
      unit: 'tray',
      description: '5 lbs — half chorizo verde, half Jalisco carnitas. Feeds 8–10 people. A Jalisco classic combination.',
      pricePerLb: 64.99,
      image: 'https://images.unsplash.com/photo-1592415499556-74fcb9f18667?w=600&auto=format&fit=crop',
      inStock: false,
      stockLbs: 0,
      options: { marinade: false, cut: false },
      popular: false,
    },
    {
      id: 'p4-1',
      vendorId: 'v4',
      name: 'Chorizo Verde',
      category: 'chorizo',
      description: 'Green chorizo made with fresh poblano, tomatillo, and herbs. A Jalisco specialty.',
      pricePerLb: 9.49,
      image: 'https://images.unsplash.com/photo-1592415499556-74fcb9f18667?w=600&auto=format&fit=crop',
      inStock: false,
      stockLbs: 0,
      options: { marinade: false, cut: false },
      popular: false,
    },
  ],
}

export const MOCK_ORDERS = [
  {
    id: 'ord-001',
    customerId: 'customer-user-1',
    vendorId: 'v1',
    vendorName: 'La Carnicería El Rancho',
    driverId: 'driver-user-1',
    driverName: 'Carlos M.',
    items: [
      { productId: 'p1-t1', name: 'Carne Asada Party Tray', pricePerLb: 64.99, quantity: 1, unit: 'tray', marinade: 'traditional', cut: null },
      { productId: 'p1-2', name: 'Chorizo Rojo', pricePerLb: 8.99, quantity: 1, cut: null },
    ],
    subtotal: 73.98,
    serviceFee: 3.70,
    deliveryFee: 4.99,
    total: 82.67,
    status: 'picked_up',
    address: '500 El Camino Real, San Jose, CA',
    createdAt: new Date(Date.now() - 25 * 60000),
    estimatedDelivery: '5–15 min',
    paymentMethod: 'card',
    paymentLast4: '4242',
  },
  {
    id: 'ord-002',
    customerId: 'customer-user-1',
    vendorId: 'v2',
    vendorName: 'Carnitas La Familia',
    driverId: 'driver-user-2',
    driverName: 'Miguel R.',
    items: [
      { productId: 'p2-t1', name: 'Carnitas Family Tray', pricePerLb: 59.99, quantity: 1, unit: 'tray', cut: null },
    ],
    subtotal: 59.99,
    serviceFee: 3.00,
    deliveryFee: 4.99,
    total: 67.98,
    status: 'delivered',
    address: '500 El Camino Real, San Jose, CA',
    createdAt: new Date(Date.now() - 2 * 24 * 3600000),
    estimatedDelivery: 'Delivered',
    paymentMethod: 'card',
    paymentLast4: '4242',
  },
]

export const MOCK_REVIEWS = {
  v1: [
    { id: 'rv-1-1', vendorId: 'v1', rating: 5, text: 'The Carne Asada Party Tray was a hit at my backyard BBQ! 5 lbs gone in 20 minutes. Everyone asked where I ordered from. Delivery was hot and fast.', reviewerName: 'Maria G.', createdAt: new Date(Date.now() - 2 * 24 * 3600000) },
    { id: 'rv-1-2', vendorId: 'v1', rating: 5, text: 'Ordered the BBQ Mix Tray for my son\'s graduation — 30 guests, everyone was satisfied. The short ribs and carne asada together are unbeatable.', reviewerName: 'Jose R.', createdAt: new Date(Date.now() - 5 * 24 * 3600000) },
    { id: 'rv-1-3', vendorId: 'v1', rating: 4, text: 'Party tray arrived on time and still hot. The citrus marinade on the carne asada is incredible. Will be ordering for every family event.', reviewerName: 'Ana L.', createdAt: new Date(Date.now() - 7 * 24 * 3600000) },
    { id: 'rv-1-4', vendorId: 'v1', rating: 5, text: 'Easiest party planning ever. Ordered 2 trays for a quinceañera. Showed up exactly as promised and the meat was perfect.', reviewerName: 'Carlos M.', createdAt: new Date(Date.now() - 10 * 24 * 3600000) },
    { id: 'rv-1-5', vendorId: 'v1', rating: 5, text: 'Roberto and his family know their craft. The BBQ tray is our go-to for every carne asada. Nothing comes close.', reviewerName: 'Sofia P.', createdAt: new Date(Date.now() - 14 * 24 * 3600000) },
  ],
  v2: [
    { id: 'rv-2-1', vendorId: 'v2', rating: 5, text: 'Carnitas Family Tray is the real deal. Crispy ends and super tender inside — exactly like Michoacán. Enough for the whole family.', reviewerName: 'Pedro M.', createdAt: new Date(Date.now() - 3 * 24 * 3600000) },
    { id: 'rv-2-2', vendorId: 'v2', rating: 5, text: 'Al Pastor Party Tray for my husband\'s birthday — he said it was the best al pastor he\'s ever had. You can taste the pineapple and the guajillo.', reviewerName: 'Carmen R.', createdAt: new Date(Date.now() - 6 * 24 * 3600000) },
    { id: 'rv-2-3', vendorId: 'v2', rating: 4, text: 'Party Mixto Tray fed 18 people easily. Great variety — everyone had something they loved. Fast delivery too.', reviewerName: 'Luis F.', createdAt: new Date(Date.now() - 9 * 24 * 3600000) },
    { id: 'rv-2-4', vendorId: 'v2', rating: 5, text: 'Ordered the Carnitas Tray for a quinceañera. 100 guests raved about it. Will order again for every party!', reviewerName: 'Isabel G.', createdAt: new Date(Date.now() - 12 * 24 * 3600000) },
  ],
  v3: [
    { id: 'rv-3-1', vendorId: 'v3', rating: 5, text: 'The A5 Wagyu Tray is absolutely worth every penny. I\'ve never tasted beef this good. Restaurant quality delivered to my door.', reviewerName: 'David K.', createdAt: new Date(Date.now() - 1 * 24 * 3600000) },
    { id: 'rv-3-2', vendorId: 'v3', rating: 4, text: 'USDA Prime Carne Asada Tray blew my family away. Dry-aged and marinated perfectly. Delivery was quick.', reviewerName: 'Rosa M.', createdAt: new Date(Date.now() - 4 * 24 * 3600000) },
    { id: 'rv-3-3', vendorId: 'v3', rating: 5, text: 'Short Rib Tray for our Korean BBQ night was next level. I\'ve tried every carnicería in LA and this is my #1.', reviewerName: 'Marco V.', createdAt: new Date(Date.now() - 8 * 24 * 3600000) },
  ],
  v4: [
    { id: 'rv-4-1', vendorId: 'v4', rating: 5, text: 'Weekend Fiesta Tray is amazing — huge variety and everything was fresh. Jalisco pride at its best!', reviewerName: 'Elena S.', createdAt: new Date(Date.now() - 15 * 24 * 3600000) },
    { id: 'rv-4-2', vendorId: 'v4', rating: 4, text: 'Chorizo + Carnitas Tray is a perfect combo. Everything made fresh every morning. You can really taste the difference.', reviewerName: 'Hector B.', createdAt: new Date(Date.now() - 20 * 24 * 3600000) },
  ],
}

export const MOCK_DRIVER_DELIVERIES = [
  {
    id: 'del-001',
    orderId: 'ord-001',
    driverId: 'driver-user-1',
    status: 'picked_up',
    vendorName: 'La Carnicería El Rancho',
    vendorAddress: '1420 Story Rd, San Jose, CA 95122',
    customerName: 'Maria G.',
    customerAddress: '500 El Camino Real, San Jose, CA 95008',
    customerPhone: '(408) 555-0199',
    items: '1 Carne Asada Party Tray + 1 lb Chorizo',
    earning: 8.50,
    pickupTime: new Date(Date.now() - 15 * 60000),
    estimatedDropoff: '5–10 min',
  },
]

export const MOCK_USERS = {
  customer: {
    id: 'customer-user-1',
    email: 'customer@demo.com',
    password: 'demo123',
    name: 'Maria García',
    role: 'customer',
    phone: '(408) 555-0199',
    address: '500 El Camino Real, San Jose, CA 95008',
    avatar: null,
  },
  vendor: {
    id: 'vendor-user-1',
    email: 'vendor@demo.com',
    password: 'demo123',
    name: 'Roberto Hernández',
    role: 'vendor',
    vendorId: 'v1',
    phone: '(408) 555-0192',
    avatar: null,
  },
  driver: {
    id: 'driver-user-1',
    email: 'driver@demo.com',
    password: 'demo123',
    name: 'Carlos Mendoza',
    role: 'driver',
    phone: '(408) 555-0288',
    vehicle: 'Toyota Corolla — Silver',
    licensePlate: '7ABC123',
    avatar: null,
    isOnline: true,
  },
  admin: {
    id: 'admin-user-1',
    email: 'admin@demo.com',
    password: 'demo123',
    name: 'Admin User',
    role: 'admin',
    phone: '(415) 555-0001',
    avatar: null,
  },
}
